import {
  type AnsweredRound,
  ConflictError,
  GateError,
  type InterviewAnswer,
  runInterviewer,
} from '@storyforge/core';
import { inTransaction, isUniqueViolation } from '@storyforge/db';
import type { ServiceContext } from './context.js';

const UNTITLED = 'Untitled book';

/** Creates a project from a pitch. The first question round is generated by advanceInterview. */
export async function createProject(
  ctx: ServiceContext,
  userId: string,
  pitch: string,
  title?: string,
) {
  const trimmed = pitch.trim();
  if (trimmed.length < 10) throw new GateError('Pitch is too short', ['Write at least a sentence']);
  return ctx.repos.projects.create(userId, trimmed, title?.trim() || UNTITLED);
}

/**
 * Moves the interview forward: returns the pending round if one is unanswered, otherwise
 * asks the interviewer for the next round or, once it is done, the draft bible.
 */
export async function advanceInterview(ctx: ServiceContext, projectId: string) {
  const project = await ctx.repos.projects.get(projectId);
  if (!project) throw new ConflictError('Project not found');
  if (project.status !== 'intake') throw new ConflictError('The interview is already finished');

  const rounds = await ctx.repos.interview.list(projectId);
  const pending = rounds.find((r) => r.answers === null);
  if (pending) return { kind: 'questions' as const, round: pending };

  const answered: AnsweredRound[] = rounds.map((r) => ({
    roundNo: r.roundNo,
    questions: r.questions,
    answers: r.answers ?? [],
  }));
  const out = await runInterviewer(ctx.agentContext(projectId), {
    pitch: project.createdFromPitch,
    rounds: answered,
  });

  if (out.kind === 'questions') {
    try {
      const round = await ctx.repos.interview.add(projectId, rounds.length + 1, out.questions);
      return { kind: 'questions' as const, round };
    } catch (err) {
      // A concurrent request saved this round first; return theirs.
      if (!isUniqueViolation(err)) throw err;
      const winner = (await ctx.repos.interview.list(projectId)).find((r) => r.answers === null);
      if (!winner) throw err;
      return { kind: 'questions' as const, round: winner };
    }
  }

  const bible = out.bible!;
  await inTransaction(ctx.db, async (repos) => {
    await repos.bibles.createVersion(projectId, {
      spine: bible.spine,
      world: bible.world,
      styleGuide: bible.styleGuide,
    });
    if (project.title === UNTITLED) await repos.projects.setTitle(projectId, bible.title);
    await repos.projects.transition(projectId, 'intake', 'bible_review');
  });
  return { kind: 'bible' as const };
}

export async function submitAnswers(
  ctx: ServiceContext,
  projectId: string,
  roundId: string,
  answers: InterviewAnswer[],
) {
  const rounds = await ctx.repos.interview.list(projectId);
  const round = rounds.find((r) => r.id === roundId);
  if (!round) throw new ConflictError('Round not found');
  const known = new Set(round.questions.map((q) => q.id));
  const unknown = answers.filter((a) => !known.has(a.questionId));
  if (unknown.length) throw new GateError('Answers reference unknown questions');
  // Unanswered questions count as skipped.
  const complete = round.questions.map(
    (q) =>
      answers.find((a) => a.questionId === q.id) ?? {
        questionId: q.id,
        kind: 'skip' as const,
        text: '',
      },
  );
  await ctx.repos.interview.answer(projectId, roundId, complete);
  return advanceInterview(ctx, projectId);
}
